[platformio]
core_dir = C:\pio

[env]
platform = https://github.com/pioarduino/platform-espressif32.git
framework = arduino
board = esp32-s3-devkitm-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = partitions_16MB_ota.csv
monitor_port = COM3
monitor_speed = 115200
upload_port = COM3
upload_speed = 921600

extra_scripts =
  pre:scripts/select_port.py
  pre:scripts/git_version.py

lib_deps =
    lvgl/lvgl @ ^8.3.11
    bblanchon/ArduinoJson @ ^7.0.4
    moononournation/GFX Library for Arduino
    bodmer/TJpg_Decoder @ ^1.1.0

build_flags =
  -DBOARD_HAS_PSRAM
  -DLV_CONF_INCLUDE_SIMPLE
  -DLV_COLOR_DEPTH=16
  -DARDUINO_USB_CDC_ON_BOOT=0
  -I include

[env:tessera]

[env:tessera_ota]
extends = env:tessera
upload_protocol = espota
upload_port = tessera.local