#!/usr/bin/env python3
"""Tessera setup wizard — get a freshly-cloned panel connected.

Gathers the per-device credentials (WiFi, Home Assistant host/port/token, time
settings), validates the HA token against your HA instance *from this PC* before
flashing, writes them to include/secrets.h (gitignored), and optionally flashes
the panel over USB and tails the serial log to confirm WiFi + HA come up.

Scope: connectivity only. Devices/tiles stay in include/config.h and are edited
in code (ideally with an LLM — see the README "Adding devices" section).

Why validate the token first: Home Assistant IP-bans a client after repeated
failed auths. Confirming the token works from the PC keeps the panel from
ban-looping on a bad token (see the README's "Known setup notes" section).

Running more than one panel? See panels.py instead — it wraps this same
credential/validation flow per panel and can tell physical boards apart.

Run it with the PlatformIO Python, which already has pyserial + platformio:

    Windows : & "$env:USERPROFILE\.platformio\penv\Scripts\python.exe" setup_wizard.py
    macOS   : ~/.platformio/penv/bin/python setup_wizard.py
    Linux   : ~/.platformio/penv/bin/python setup_wizard.py

Plain `python setup_wizard.py` also works; the flash/serial steps warn if
platformio/pyserial aren't importable and tell you how to do them by hand. The
serial port is auto-detected (COMx / /dev/cu.* / /dev/ttyUSB*), so you're not
tied to a specific port number.
"""

import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))   # repo root (this script lives here)
SECRETS_PATH = os.path.join(ROOT, "include", "secrets.h")
UPLOAD_ENV = "tessera"

# USB-serial chips this board (and common ESP32 dev boards) show up as. Used to
# auto-detect the panel's port across Windows (COMx), macOS (/dev/cu.*) and Linux
# (/dev/ttyUSB*, /dev/ttyACM*) so users aren't tied to the author's COM7.
SERIAL_VIDS = {0x1A86, 0x10C4, 0x0403, 0x303A, 0x239A}  # CH34x, CP210x, FTDI, Espressif, Adafruit
SERIAL_KEYWORDS = ("ch340", "ch341", "cp210", "cp2102", "ftdi", "usb serial",
                   "silicon labs", "wchusbserial", "usb jtag", "esp32",
                   "usbserial", "usbmodem")

# Ordered fields the wizard manages. (key, label, default, is_secret)
FIELDS = [
    ("WIFI_SSID",     "WiFi network name (SSID)",        "",                          False),
    ("WIFI_PASSWORD", "WiFi password",                   "",                          True),
    ("HA_HOST",       "Home Assistant host IP",          "",                          False),
    ("HA_PORT",       "Home Assistant port",             "8123",                      False),
    ("HA_TOKEN",      "HA long-lived access token",      "",                          True),
    ("TZ_INFO",       "Timezone",                        "PST8PDT,M3.2.0,M11.1.0",    False),
    ("NTP_SERVER",    "NTP server",                      "pool.ntp.org",              False),
]

# Short guidance printed just above a field's prompt, to point users at where to
# find a value. Keyed by field name.
HINTS = {
    "HA_TOKEN": (
        "    Where to get this: in Home Assistant, click your user profile\n"
        "    (bottom-left) -> Security tab -> scroll to 'Long-lived access\n"
        "    tokens' -> Create Token. Copy it now; HA shows it only once."
    ),
}

# Human-readable timezones -> the POSIX TZ string configTzTime() needs. Curated
# common zones; users elsewhere can type a raw POSIX string at the prompt. DST
# rules included so clocks shift automatically.
TIMEZONES = [
    ("US Eastern (New York)",          "EST5EDT,M3.2.0,M11.1.0"),
    ("US Central (Chicago)",           "CST6CDT,M3.2.0,M11.1.0"),
    ("US Mountain (Denver)",           "MST7MDT,M3.2.0,M11.1.0"),
    ("US Arizona (no DST)",            "MST7"),
    ("US Pacific (Los Angeles)",       "PST8PDT,M3.2.0,M11.1.0"),
    ("US Alaska (Anchorage)",          "AKST9AKDT,M3.2.0,M11.1.0"),
    ("US Hawaii (no DST)",             "HST10"),
    ("UK / Ireland (London)",          "GMT0BST,M3.5.0/1,M10.5.0"),
    ("Central Europe (Paris/Berlin)",  "CET-1CEST,M3.5.0,M10.5.0/3"),
    ("Eastern Europe (Athens)",        "EET-2EEST,M3.5.0/3,M10.5.0/4"),
    ("India (Kolkata)",                "IST-5:30"),
    ("China (Shanghai)",               "CST-8"),
    ("Japan (Tokyo)",                  "JST-9"),
    ("Australia Eastern (Sydney)",     "AEST-10AEDT,M10.1.0,M4.1.0/3"),
    ("UTC",                            "UTC0"),
]

SECRETS_HEADER = """#pragma once

// secrets.h — per-device credentials. GITIGNORED; never commit real values.
//
// Generated by setup_wizard.py. Holds everything secret or
// deployment-specific about *connecting*: WiFi, the Home Assistant
// host/port/token, and time settings. What the panel *displays* (entities,
// tiles, icons, pins) lives in config.h. Re-run the wizard to change these.
"""


# --- small console helpers ---------------------------------------------------

def mask(value):
    """Show a secret as f***t so the user can confirm without printing it."""
    if not value:
        return ""
    if len(value) <= 4:
        return "*" * len(value)
    return f"{value[0]}{'*' * (len(value) - 2)}{value[-1]}"


def read_existing(path=SECRETS_PATH):
    """Parse an existing secrets.h (if any) into {KEY: value} for prefill.

    Defaults to include/secrets.h; panels.py passes a panel profile's own
    secrets.h when copying credentials between panels."""
    values = {}
    if not os.path.exists(path):
        return values
    pattern = re.compile(r'#define\s+(\w+)\s+"((?:[^"\\]|\\.)*)"')
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = pattern.search(line)
            if m:
                # un-escape \" and \\ back to raw text
                values[m.group(1)] = m.group(2).replace('\\"', '"').replace("\\\\", "\\")
    # HA_PORT is a bare int in the header; grab it separately.
    with open(path, encoding="utf-8") as f:
        m = re.search(r"#define\s+HA_PORT\s+(\d+)", f.read())
        if m:
            values["HA_PORT"] = m.group(1)
    return values


def ask(label, default, is_secret):
    """Prompt once. Enter keeps the default. Returns the chosen string."""
    shown = mask(default) if is_secret else default
    suffix = f" [{shown}]" if default else ""
    while True:
        reply = input(f"  {label}{suffix}: ").strip()
        if reply:
            return reply
        if default:
            return default
        print("    (required - please enter a value)")


def ask_timezone(current):
    """Show the human-readable timezone menu and return a POSIX TZ string.

    Enter keeps the current value; a number picks from the list; anything else is
    accepted as a raw POSIX TZ string (escape hatch for unlisted zones)."""
    print("\n  Timezone - pick a number, or type a POSIX TZ string for elsewhere:")
    for i, (name, _) in enumerate(TIMEZONES, 1):
        print(f"    {i:2}. {name}")
    cur_name = next((n for n, p in TIMEZONES if p == current), None)
    if current:
        shown = f"{cur_name}" if cur_name else current
        prompt = f"  Choice [1-{len(TIMEZONES)}] (Enter keeps {shown}): "
    else:
        prompt = f"  Choice [1-{len(TIMEZONES)}]: "
    while True:
        reply = input(prompt).strip()
        if not reply:
            if current:
                return current
            print("    (please choose a timezone)")
            continue
        if reply.isdigit():
            idx = int(reply)
            if 1 <= idx <= len(TIMEZONES):
                name, posix = TIMEZONES[idx - 1]
                print(f"    -> {name}: {posix}")
                return posix
            print(f"    (out of range - pick 1-{len(TIMEZONES)})")
            continue
        return reply  # treat as a raw POSIX TZ string


def c_escape(value):
    r"""Escape a Python string for a C "..." literal (\ and " only)."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


# --- HA token validation -----------------------------------------------------

def validate_ha(host, port, token):
    """GET http://host:port/api/ with the bearer token. Returns (ok, message)."""
    url = f"http://{host}:{port}/api/"
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}"})
    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            body = resp.read().decode("utf-8", "replace")
            if resp.status == 200 and "API running" in body:
                return True, "HA reachable and token accepted."
            return True, f"HA reachable (HTTP {resp.status}); token looks usable."
    except urllib.error.HTTPError as e:
        if e.code == 401:
            return False, "HTTP 401 - token rejected. Check the long-lived token."
        if e.code == 403:
            return False, "HTTP 403 - token forbidden. Generate a fresh long-lived token."
        return False, f"HTTP {e.code} from HA - unexpected; check host/port."
    except urllib.error.URLError as e:
        return False, f"Could not reach {host}:{port} ({e.reason}). Check host/port and that HA is up."
    except Exception as e:  # noqa: BLE001 — surface anything unexpected plainly
        return False, f"Validation error: {e}"


# --- secrets.h writer --------------------------------------------------------

def write_secrets(values, path=SECRETS_PATH):
    """Write values to a secrets.h. Defaults to include/secrets.h; panels.py
    passes a panel profile's own path (panels/<name>/secrets.h)."""
    lines = [SECRETS_HEADER, "", "// WiFi"]
    lines.append(f'#define WIFI_SSID      "{c_escape(values["WIFI_SSID"])}"')
    lines.append(f'#define WIFI_PASSWORD  "{c_escape(values["WIFI_PASSWORD"])}"')
    lines.append("")
    lines.append("// Home Assistant")
    lines.append(f'#define HA_HOST   "{c_escape(values["HA_HOST"])}"')
    lines.append(f'#define HA_PORT   {int(values["HA_PORT"])}')
    lines.append(f'#define HA_TOKEN  "{c_escape(values["HA_TOKEN"])}"')
    lines.append("")
    lines.append("// Time")
    lines.append(f'#define TZ_INFO    "{c_escape(values["TZ_INFO"])}"')
    lines.append(f'#define NTP_SERVER "{c_escape(values["NTP_SERVER"])}"')
    lines.append("")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"\n  Wrote {path}")


# --- flashing + serial confirm ----------------------------------------------

def detect_serial_port():
    """Find the panel's USB-serial port cross-platform. Returns a device string
    (e.g. 'COM7', '/dev/cu.usbserial-110') or None if it can't be determined.

    Prefers ports whose USB chip looks like an ESP32 dev board; if several match
    (or none do but ports exist), asks the user to pick."""
    try:
        from serial.tools import list_ports
    except ImportError:
        return None  # pyserial missing — caller falls back to platformio's own detection
    ports = list(list_ports.comports())
    if not ports:
        return None

    def looks_like_board(p):
        if getattr(p, "vid", None) in SERIAL_VIDS:
            return True
        blob = f"{p.description or ''} {p.device or ''} {p.manufacturer or ''}".lower()
        return any(k in blob for k in SERIAL_KEYWORDS)

    pool = [p for p in ports if looks_like_board(p)] or ports
    if len(pool) == 1:
        print(f"  Detected serial port: {pool[0].device} ({pool[0].description})")
        return pool[0].device
    print("\n  Multiple serial ports found:")
    for i, p in enumerate(pool, 1):
        print(f"    {i}. {p.device}  ({p.description})")
    while True:
        sel = input(f"  Pick the panel's port [1-{len(pool)}]: ").strip()
        if sel.isdigit() and 1 <= int(sel) <= len(pool):
            return pool[int(sel) - 1].device


def find_platformio():
    for name in ("platformio", "pio"):
        path = shutil.which(name)
        if path:
            return [path]
    # Fall back to the standard PlatformIO penv install.
    home = os.path.expanduser("~")
    for rel in (
        os.path.join(".platformio", "penv", "Scripts", "platformio.exe"),
        os.path.join(".platformio", "penv", "bin", "platformio"),
    ):
        cand = os.path.join(home, rel)
        if os.path.exists(cand):
            return [cand]
    return None


def flash(port):
    pio = find_platformio()
    if not pio:
        print("\n  platformio not found on PATH. Flash manually with:")
        print(f"    platformio run -e {UPLOAD_ENV} -t upload")
        return False
    env = dict(os.environ, PYTHONIOENCODING="utf-8")
    cmd = pio + ["run", "-e", UPLOAD_ENV, "-t", "upload"]
    # Override platformio.ini's pinned upload_port so this works on any machine.
    if port:
        cmd += ["--upload-port", port]
    where = port or "the platformio.ini-configured port"
    print(f"\n  Flashing (env {UPLOAD_ENV}) over USB on {where}...\n")
    result = subprocess.run(cmd, cwd=ROOT, env=env)
    if result.returncode != 0:
        print("\n  Flash failed. Check the panel is on USB and the COM port is free.")
        return False
    print("\n  Flash complete.")
    return True


def serial_confirm(port):
    if not port:
        print("\n  No serial port detected - confirm manually with: python serial_read.py")
        return
    try:
        import serial  # pyserial
    except ImportError:
        print("\n  pyserial not available - confirm manually with: python serial_read.py")
        return
    try:
        s = serial.Serial(port, 115200, timeout=0.5)
    except Exception as e:  # noqa: BLE001
        print(f"\n  Could not open {port} ({e}). Confirm manually: python serial_read.py")
        return
    # Toggle DTR to reset the board, then watch the boot log (same as serial_read.py).
    s.setDTR(False); _sleep(0.1); s.setDTR(True); _sleep(0.1)
    print(f"\n  Watching {port} for WiFi + HA connect (up to 60s)...\n")
    import time
    end = time.time() + 60
    wifi_ok = ha_ok = False
    while time.time() < end and not (wifi_ok and ha_ok):
        line = s.readline()
        if not line:
            continue
        text = line.decode("utf-8", "replace").rstrip()
        print(f"    {text}")
        if "WiFi connected" in text:
            wifi_ok = True
        if "HA authenticated" in text:
            ha_ok = True
    s.close()
    print()
    print(f"  WiFi: {'OK' if wifi_ok else 'NOT SEEN'}    "
          f"HA: {'OK' if ha_ok else 'NOT SEEN'}")
    if wifi_ok and ha_ok:
        print("  Baseline connectivity confirmed. You're ready to add devices in config.h.")
    else:
        print("  Did not see both within 60s - re-run the wizard or check serial_read.py output.")


def _sleep(seconds):
    import time
    time.sleep(seconds)


# --- main --------------------------------------------------------------------

def main():
    print("\nTessera setup wizard")
    print("====================")
    print("Gathers WiFi + Home Assistant credentials, validates the HA token,")
    print("writes include/secrets.h, and (optionally) flashes + confirms.\n")

    existing = read_existing()
    if existing:
        print("Found an existing secrets.h - press Enter to keep each current value.\n")

    values = {}
    for key, label, default, is_secret in FIELDS:
        if key in HINTS:
            print(HINTS[key])
        if key == "TZ_INFO":
            values[key] = ask_timezone(existing.get(key, default))
        else:
            values[key] = ask(label, existing.get(key, default), is_secret)

    # Validate the HA token from this PC before writing/flashing (avoids HA IP-ban).
    while True:
        print("\n  Validating HA token against your HA instance...")
        ok, msg = validate_ha(values["HA_HOST"], values["HA_PORT"], values["HA_TOKEN"])
        print(f"  -> {msg}")
        if ok:
            break
        choice = input("\n  Token/host validation failed. (r)e-enter Home Assistant "
                       "information, (c)ontinue anyway, or (q)uit? [r/c/q]: ").strip().lower()
        if choice == "c":
            break
        if choice == "q":
            print("  Aborted - secrets.h not written.")
            return 1
        for key in ("HA_HOST", "HA_PORT", "HA_TOKEN"):
            label = next(f[1] for f in FIELDS if f[0] == key)
            is_secret = next(f[3] for f in FIELDS if f[0] == key)
            values[key] = ask(label, values[key], is_secret)

    write_secrets(values)

    if input("\n  Flash the panel over USB now? [y/N]: ").strip().lower() == "y":
        port = detect_serial_port()  # None -> platformio auto-detects for flash
        if flash(port):
            if input("  Watch serial to confirm WiFi + HA connect? [Y/n]: ").strip().lower() != "n":
                serial_confirm(port)
    else:
        print(f"\n  Skipped flashing. When ready: platformio run -e {UPLOAD_ENV} -t upload")

    print("\nDone.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\nAborted.")
        sys.exit(130)
